In [2]:
#importar librerias 
import numpy as np

In [ ]:
#generar matriz de transicion
m1 = np.matrix([[0.80,0.15,0.05],[0.3,0.6,0.1],[0.4,0.3,0.3]])
m1

matrix([[0.8 , 0.15, 0.05],
        [0.3 , 0.6 , 0.1 ],
        [0.4 , 0.3 , 0.3 ]])

In [5]:
# cual es la probabilidad de que al dia siguiente este en mantenimiento?
# F,M,A
v3 = np.matrix([[1,0,0]])
v3_resultado = np.dot(v3,m1)
v3_resultado
print("La probabilidad de que al dia siguiente este en mantenimiento es: ",v3_resultado[0,1]*100)

La probabilidad de que al dia siguiente este en mantenimiento es:  15.0


In [10]:
#4 probabilidad a dos dias de estar en funcionamiento a mantenimiento 
p2 = np.dot(m1,m1)
p2

v4 = np.matrix([[1,0,0]])
v4_resultado = np.dot(v4,p2)
v4_resultado
print("La probabilidad de pasar al dia sigueinte de funioanando a averaido es:", round(v4_resultado[0,2]*100,1))

La probabilidad de pasar al dia sigueinte de funioanando a averaido es: 7.0


In [14]:
#detectar matriz estable
for i in range(100):
    if i == 0:
        m_aux = np.dot(m1, m1)
        print(m_aux)
        print("1------------------", i + 1)
    else:
        y = i+1
        m_aux_anterior = m_aux
        m_aux = np.dot(m_aux, m1)
        print(m_aux)
        if (np.array_equal(m_aux, m_aux_anterior)):
            break
        print("------------------", i+1)
        print()
        print("la matriz estable es: \n" ,np.round(m_aux,4))

vector_estable = np.round(m_aux[0],4)
#convertir a porcentaje
porcentajes = vector_estable * 100
print("Distribucion estable estacionaria en %")
print(f"funcionando:{porcentajes[0,0]:.2f}")
print(f"mantenimiento:{porcentajes[0,1]:.2f}")
print(f"averiado:{porcentajes[0,2]:.2f}")

[[0.705 0.225 0.07 ]
 [0.46  0.435 0.105]
 [0.53  0.33  0.14 ]]
1------------------ 1
[[0.6595  0.26175 0.07875]
 [0.5405  0.3615  0.098  ]
 [0.579   0.3195  0.1015 ]]
------------------ 2

la matriz estable es: 
 [[0.6595 0.2618 0.0788]
 [0.5405 0.3615 0.098 ]
 [0.579  0.3195 0.1015]]
[[0.637625 0.2796   0.082775]
 [0.58005  0.327375 0.092575]
 [0.59965  0.309    0.09135 ]]
------------------ 3

la matriz estable es: 
 [[0.6376 0.2796 0.0828]
 [0.58   0.3274 0.0926]
 [0.5996 0.309  0.0914]]
[[0.62709    0.28823625 0.08467375]
 [0.5992825  0.311205   0.0895125 ]
 [0.60896    0.3027525  0.0882875 ]]
------------------ 4

la matriz estable es: 
 [[0.6271 0.2882 0.0847]
 [0.5993 0.3112 0.0895]
 [0.609  0.3028 0.0883]]
[[0.62201238 0.29240738 0.08558025]
 [0.6085925  0.30346912 0.08793837]
 [0.61330875 0.29948175 0.0872095 ]]
------------------ 5

la matriz estable es: 
 [[0.622  0.2924 0.0856]
 [0.6086 0.3035 0.0879]
 [0.6133 0.2995 0.0872]]
[[0.61956421 0.29442036 0.08601543]
 [0.6130900