La cerveceria mas importante del mundo (GUINNESS), ha contratado a un analista de investigacion de operaciones, para analizar su pocision en el mercado. Estan preocupados, en especial por su mayor competidos (HEINEKEL). El analista piensa que el cambio de marca se puede modelar con una cadena de markov, incluyendo 3 estados; Los estados G y H representan a los clientes que beben cerveza producida por las mencionadas cervecerias y en el estado I representa a todas las demas marcas. Los datos se toman cada mes y el analista a construido la siguiente matriz de trancicion de datos historicos.

[G = 0.7 0.2 0.1]
[H = 0.2 0.75 0.05]
[I = 0.1 0.1 0.8]

cuales son los porcentajes de mercado en el estado estable para las dos cervezerias mas grandes?

In [1]:
import numpy as np
m1 = np.matrix([[0.7, 0.2, 0.1], [0.2, 0.75, 0.05], [0.1,0.1,0.8]])
m1

matrix([[0.7 , 0.2 , 0.1 ],
        [0.2 , 0.75, 0.05],
        [0.1 , 0.1 , 0.8 ]])

In [2]:
m_aux = np.matrix([[], []])
m_aux_anterior = np.matrix([[], []])

In [3]:
#detectar matriz estable
for i in range(100):
    if i == 0:
        m_aux = np.dot(m1, m1)
        print(m_aux)
        print("1------------------", i + 1)
    else:
        y = i+1
        m_aux_anterior = m_aux
        m_aux = np.dot(m_aux, m1)
        print(m_aux)
        if (np.array_equal(m_aux, m_aux_anterior)):
            break
        print("------------------", i+1)
        print()
        print("la matriz estable es: \n" ,np.round(m_aux,4))

[[0.54   0.3    0.16  ]
 [0.295  0.6075 0.0975]
 [0.17   0.175  0.655 ]]
1------------------ 1
[[0.454    0.349    0.197   ]
 [0.33775  0.524375 0.137875]
 [0.2195   0.23075  0.54975 ]]
------------------ 2

la matriz estable es: 
 [[0.454  0.349  0.197 ]
 [0.3378 0.5244 0.1379]
 [0.2195 0.2308 0.5498]]
[[0.4073     0.37225    0.22045   ]
 [0.3550875  0.47461875 0.17029375]
 [0.254775   0.2719375  0.4732875 ]]
------------------ 3

la matriz estable es: 
 [[0.4073 0.3722 0.2204]
 [0.3551 0.4746 0.1703]
 [0.2548 0.2719 0.4733]]
[[0.381605   0.3826925  0.2357025 ]
 [0.36051437 0.44401094 0.19547469]
 [0.28005875 0.30223688 0.41770438]]
------------------ 4

la matriz estable es: 
 [[0.3816 0.3827 0.2357]
 [0.3605 0.444  0.1955]
 [0.2801 0.3022 0.4177]]
[[0.36723225 0.38691062 0.24585713]
 [0.36070972 0.42465855 0.21463173]
 [0.29825894 0.32445984 0.37728122]]
------------------ 5

la matriz estable es: 
 [[0.3672 0.3869 0.2459]
 [0.3607 0.4247 0.2146]
 [0.2983 0.3245 0.3773]]
[[0.3590304

In [5]:
# porcentaje de cada estado
print("porcentaje estado 1:", np.round(m_aux[0,0]*100, 4)
      ,"\nporcentaje estado 2:", np.round(m_aux[0,1]*100, 4)
      ,"\nporcentaje estado 3:", np.round(m_aux[0,2]*100, 4))


porcentaje estado 1: 34.6154 
porcentaje estado 2: 38.4615 
porcentaje estado 3: 26.9231


In [8]:
#poblacion inicial 
poblacion_incial = np.matrix([[6000,3000,1000]])
poblacion_incial



matrix([[6000, 3000, 1000]])

In [13]:
print("Población inicial:----V0")
for z in range(50):
    if z == 0:
        poblacion_inicial = np.dot(poblacion_incial,m1)
        poblacion_inicial = np.round(poblacion_inicial,2)
        print("Poblacion principal")
        print("----------------------------------",z+1)
    else:
        poblacion_anterior = poblacion_inicial
        poblacion_inicial = np.dot(poblacion_inicial,m1)
        poblacion_inicial = np.round(poblacion_inicial,2)
        
        if np.array_equal(poblacion_inicial,poblacion_anterior):
            print("Poblacion inicial y anterior son iguales")
            print("--------------------------Numero de iteraciones: ",str(z)+"----------------------------------")
            poblacion_inicial = np.round(poblacion_inicial,0)
            poblacion_inicial = poblacion_inicial.astype(int)
            print("Poblacion Final: ",poblacion_inicial)
            print("N --------------------------------------",z+1)
            break
    print(poblacion_inicial)
    print("Poblacion se estabiliza en la iteración: ",z+1)

Población inicial:----V0
Poblacion principal
---------------------------------- 1
[[4900. 3550. 1550.]]
Poblacion se estabiliza en la iteración:  1
[[4295.  3797.5 1907.5]]
Poblacion se estabiliza en la iteración:  2
[[3956.75 3897.88 2145.38]]
Poblacion se estabiliza en la iteración:  3
[[3763.84 3929.3  2306.87]]
Poblacion se estabiliza en la iteración:  4
[[3651.24 3930.43 2418.35]]
Poblacion se estabiliza en la iteración:  5
[[3583.79 3919.91 2496.33]]
Poblacion se estabiliza en la iteración:  6
[[3542.27 3906.32 2551.44]]
Poblacion se estabiliza en la iteración:  7
[[3516.   3893.34 2590.7 ]]
Poblacion se estabiliza en la iteración:  8
[[3498.94 3882.28 2618.83]]
Poblacion se estabiliza en la iteración:  9
[[3487.6  3873.38 2639.07]]
Poblacion se estabiliza en la iteración:  10
[[3479.9  3866.46 2653.69]]
Poblacion se estabiliza en la iteración:  11
[[3474.59 3861.19 2664.27]]
Poblacion se estabiliza en la iteración:  12
[[3470.88 3857.24 2671.93]]
Poblacion se estabiliza en la it