In [53]:
#ejemplo de matriz 3x3, determinar la estable
import numpy as np
m1 = np.matrix([[0.97, 0.02, 0.01], [0.6, 0.3, 0.1], [0.2,0.1,0.7]])
m1

matrix([[0.97, 0.02, 0.01],
        [0.6 , 0.3 , 0.1 ],
        [0.2 , 0.1 , 0.7 ]])

In [54]:
m_aux = np.matrix([[], []])
m_aux_anterior = np.matrix([[], []])

In [55]:
#detectar matriz estable
for i in range(100):
    if i == 0:
        m_aux = np.dot(m1, m1)
        print(m_aux)
        print("1------------------", i + 1)
    else:
        y = i+1
        m_aux_anterior = m_aux
        m_aux = np.dot(m_aux, m1)
        print(m_aux)
        if (np.array_equal(m_aux, m_aux_anterior)):
            break
        print("------------------", i+1)
        print()
        print("la matriz estable es: \n" ,np.round(m_aux,4))

[[0.9549 0.0264 0.0187]
 [0.782  0.112  0.106 ]
 [0.394  0.104  0.502 ]]
1------------------ 1
[[0.945833 0.028888 0.025279]
 [0.84694  0.05984  0.09322 ]
 [0.54498  0.08928  0.36574 ]]
------------------ 2

la matriz estable es: 
 [[0.9458 0.0289 0.0253]
 [0.8469 0.0598 0.0932]
 [0.545  0.0893 0.3657]]
[[0.93984661 0.03011096 0.03004243]
 [0.8760798  0.0442128  0.0797074 ]
 [0.6553466  0.0742576  0.2703958 ]]
------------------ 3

la matriz estable es: 
 [[0.9398 0.0301 0.03  ]
 [0.8761 0.0442 0.0797]
 [0.6553 0.0743 0.2704]]
[[0.93572627 0.03083446 0.03343926]
 [0.89226657 0.03875618 0.06897726]
 [0.73431992 0.06242379 0.20325629]]
------------------ 4

la matriz estable es: 
 [[0.9357 0.0308 0.0334]
 [0.8923 0.0388 0.069 ]
 [0.7343 0.0624 0.2033]]
[[0.93284302 0.03130879 0.03584819]
 [0.90254773 0.03636991 0.06108236]
 [0.79039586 0.05373916 0.15586498]]
------------------ 5

la matriz estable es: 
 [[0.9328 0.0313 0.0358]
 [0.9025 0.0364 0.0611]
 [0.7904 0.0537 0.1559]]
[[0.9308126

In [56]:
m_aux = np.round(m_aux, 3)
m_aux

array([[0.926, 0.032, 0.042],
       [0.926, 0.032, 0.042],
       [0.926, 0.032, 0.042]])

In [57]:
poblacion_inicial = np.matrix([[100,0,0]])
poblacion_inicial

matrix([[100,   0,   0]])

In [58]:
print("Población inicial:----V0")
for z in range(20):
    if z == 0:
        poblacion_inicial = np.dot(poblacion_inicial,m1)
        poblacion_inicial = np.round(poblacion_inicial,2)
        print("Poblacion principal")
        print("----------------------------------",z+1)
    else:
        poblacion_anterior = poblacion_inicial
        poblacion_inicial = np.dot(poblacion_inicial,m1)
        poblacion_inicial = np.round(poblacion_inicial,2)
        
        if np.array_equal(poblacion_inicial,poblacion_anterior):
            print("Poblacion inicial y anterior son iguales")
            print("--------------------------Numero de iteraciones: ",str(z)+"----------------------------------")
            poblacion_inicial = np.round(poblacion_inicial,0)
            poblacion_inicial = poblacion_inicial.astype(int)
            print("Poblacion Final: ",poblacion_inicial)
            print("N --------------------------------------",z+1)
            break
    print(poblacion_inicial)
    print("Poblacion se estabiliza en la iteración: ",z+1)

Población inicial:----V0
Poblacion principal
---------------------------------- 1
[[97.  2.  1.]]
Poblacion se estabiliza en la iteración:  1
[[95.49  2.64  1.87]]
Poblacion se estabiliza en la iteración:  2
[[94.58  2.89  2.53]]
Poblacion se estabiliza en la iteración:  3
[[93.98  3.01  3.01]]
Poblacion se estabiliza en la iteración:  4
[[93.57  3.08  3.35]]
Poblacion se estabiliza en la iteración:  5
[[93.28  3.13  3.59]]
Poblacion se estabiliza en la iteración:  6
[[93.08  3.16  3.76]]
Poblacion se estabiliza en la iteración:  7
[[92.94  3.19  3.88]]
Poblacion se estabiliza en la iteración:  8
[[92.84  3.2   3.96]]
Poblacion se estabiliza en la iteración:  9
[[92.77  3.21  4.02]]
Poblacion se estabiliza en la iteración:  10
[[92.72  3.22  4.06]]
Poblacion se estabiliza en la iteración:  11
[[92.68  3.23  4.09]]
Poblacion se estabiliza en la iteración:  12
[[92.66  3.23  4.11]]
Poblacion se estabiliza en la iteración:  13
[[92.64  3.23  4.13]]
Poblacion se estabiliza en la iteración:

In [59]:
#Resolver los cuestionamientos
autos = 100
autos_en_taller = autos * (m_aux[2,1]+m_aux[2,2])
print("Autos promedio en el taller: ",np.round(autos_en_taller,1))

Autos promedio en el taller:  7.4


In [62]:
#calcular la utilidad
utilidad = 50
rep_men = 100
rep_may = 150
utilidad_general = (utilidad*(m_aux[2,0])) - (rep_men*(m_aux[2,1])) - (rep_may*(m_aux[2,2]))
print("utilidad anual:", utilidad_general)
print("utilidad anual:", round(utilidad_general*365))

utilidad anual: 36.8
utilidad anual: 13432
