In [19]:
#importar librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
#matriz a trabajar 
matriz = np.array([[.25,.50,.25], [.05,.90,.05], [.10,.50,.40]])
matriz

array([[0.25, 0.5 , 0.25],
       [0.05, 0.9 , 0.05],
       [0.1 , 0.5 , 0.4 ]])

In [23]:
#detectar matriz estable
for i in range(100):
    if i == 0:
        m_aux = np.dot(matriz, matriz)
        print(m_aux)
        print("1------------------", i + 1)
    else:
        y = i+1
        m_aux_anterior = m_aux
        m_aux = np.dot(m_aux, matriz)
        print(m_aux)
        if (np.array_equal(m_aux, m_aux_anterior)):
            break
        print("------------------", i+1)
        print()
        print("la matriz estable es: \n" ,np.round(m_aux,4))


[[0.1125 0.7    0.1875]
 [0.0625 0.86   0.0775]
 [0.09   0.7    0.21  ]]
1------------------ 1
[[0.081875 0.78     0.138125]
 [0.066375 0.844    0.089625]
 [0.0785   0.78     0.1415  ]]
------------------ 2

la matriz estable es: 
 [[0.0819 0.78   0.1381]
 [0.0664 0.844  0.0896]
 [0.0785 0.78   0.1415]]
[[0.07328125 0.812      0.11471875]
 [0.06775625 0.8376     0.09464375]
 [0.072775   0.812      0.115225  ]]
------------------ 3

la matriz estable es: 
 [[0.0733 0.812  0.1147]
 [0.0678 0.8376 0.0946]
 [0.0728 0.812  0.1152]]
[[0.07039219 0.8248     0.10480781]
 [0.06828344 0.83504    0.09667656]
 [0.07031625 0.8248     0.10488375]]
------------------ 4

la matriz estable es: 
 [[0.0704 0.8248 0.1048]
 [0.0683 0.835  0.0967]
 [0.0703 0.8248 0.1049]]
[[0.06931883 0.82992    0.10076117]
 [0.06849052 0.834016   0.09749348]
 [0.06930744 0.82992    0.10077256]]
------------------ 5

la matriz estable es: 
 [[0.0693 0.8299 0.1008]
 [0.0685 0.834  0.0975]
 [0.0693 0.8299 0.1008]]
[[0.0689018